language: clojure
script: lein uberjar!
before_deploy:
  - openssl aes-256-cbc -K $encrypted_a1fa50160860_key -iv $encrypted_a1fa50160860_iv -in signkey.asc.enc -out signkey.asc -d
  - gpg --fast-import signkey.asc
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: "./target/*.jar"
    on:
      branch: master
      tags: true
  - provider: script
    skip_cleanup: true
    script: lein deploy release
    on:
      branch: master
      tags: true